//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonalSite {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Texts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Texts() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PersonalSite.Texts", typeof(Texts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Message ähnelt.
        /// </summary>
        public static string ContentCaption {
            get {
                return ResourceManager.GetString("ContentCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Date ähnelt.
        /// </summary>
        public static string DateCaption {
            get {
                return ResourceManager.GetString("DateCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Actions ähnelt.
        /// </summary>
        public static string DlgActions {
            get {
                return ResourceManager.GetString("DlgActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add ähnelt.
        /// </summary>
        public static string DlgAdd {
            get {
                return ResourceManager.GetString("DlgAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Back to List ähnelt.
        /// </summary>
        public static string DlgBacktoList {
            get {
                return ResourceManager.GetString("DlgBacktoList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Blogs ähnelt.
        /// </summary>
        public static string DlgBlogLink {
            get {
                return ResourceManager.GetString("DlgBlogLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Blog List ähnelt.
        /// </summary>
        public static string DlgBlogList {
            get {
                return ResourceManager.GetString("DlgBlogList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cancel ähnelt.
        /// </summary>
        public static string DlgCancel {
            get {
                return ResourceManager.GetString("DlgCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete ähnelt.
        /// </summary>
        public static string DlgDelete {
            get {
                return ResourceManager.GetString("DlgDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dragons-Website ähnelt.
        /// </summary>
        public static string DlgDragonSite {
            get {
                return ResourceManager.GetString("DlgDragonSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Edit ähnelt.
        /// </summary>
        public static string DlgEdit {
            get {
                return ResourceManager.GetString("DlgEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Home ähnelt.
        /// </summary>
        public static string DlgHomeLink {
            get {
                return ResourceManager.GetString("DlgHomeLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Icon ähnelt.
        /// </summary>
        public static string DlgIcon {
            get {
                return ResourceManager.GetString("DlgIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This Site is owned and managed by Dragonsfure ähnelt.
        /// </summary>
        public static string DlgPrivacyHeader {
            get {
                return ResourceManager.GetString("DlgPrivacyHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Privacy ähnelt.
        /// </summary>
        public static string DlgPrivacyLink {
            get {
                return ResourceManager.GetString("DlgPrivacyLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Privacy Policy ähnelt.
        /// </summary>
        public static string DlgPrivacyPolicy {
            get {
                return ResourceManager.GetString("DlgPrivacyPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please dont cry about something, it can be taken down real fast. ähnelt.
        /// </summary>
        public static string DlgPrivacyTextOne {
            get {
                return ResourceManager.GetString("DlgPrivacyTextOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die For any Issues or questions, contact Dragonsfure over any Social-Media that is linked. ähnelt.
        /// </summary>
        public static string DlgPrivacyTextTwo {
            get {
                return ResourceManager.GetString("DlgPrivacyTextTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save ähnelt.
        /// </summary>
        public static string DlgSave {
            get {
                return ResourceManager.GetString("DlgSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Send Mail ähnelt.
        /// </summary>
        public static string DlgSendMail {
            get {
                return ResourceManager.GetString("DlgSendMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Skills ähnelt.
        /// </summary>
        public static string DlgSkillLink {
            get {
                return ResourceManager.GetString("DlgSkillLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Skill List ähnelt.
        /// </summary>
        public static string DlgSkillList {
            get {
                return ResourceManager.GetString("DlgSkillList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die From: ähnelt.
        /// </summary>
        public static string FromMailCaption {
            get {
                return ResourceManager.GetString("FromMailCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Icon-Link ähnelt.
        /// </summary>
        public static string IconCaption {
            get {
                return ResourceManager.GetString("IconCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Login ähnelt.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Name ähnelt.
        /// </summary>
        public static string NameCaption {
            get {
                return ResourceManager.GetString("NameCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Password ähnelt.
        /// </summary>
        public static string PasswordCaption {
            get {
                return ResourceManager.GetString("PasswordCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Programming Language ähnelt.
        /// </summary>
        public static string ProgrammingCaption {
            get {
                return ResourceManager.GetString("ProgrammingCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Progress ähnelt.
        /// </summary>
        public static string ProgressCaption {
            get {
                return ResourceManager.GetString("ProgressCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Short Info ähnelt.
        /// </summary>
        public static string ShortInfoCaption {
            get {
                return ResourceManager.GetString("ShortInfoCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Subject ähnelt.
        /// </summary>
        public static string SubjectCaption {
            get {
                return ResourceManager.GetString("SubjectCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Text ähnelt.
        /// </summary>
        public static string TextCaption {
            get {
                return ResourceManager.GetString("TextCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Title ähnelt.
        /// </summary>
        public static string TitleCaption {
            get {
                return ResourceManager.GetString("TitleCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tutorial ähnelt.
        /// </summary>
        public static string TutorialCaption {
            get {
                return ResourceManager.GetString("TutorialCaption", resourceCulture);
            }
        }
    }
}
